- name: Reset kubeadm
  shell: kubeadm reset
  become: yes

#- name: Join kubeadm
#  shell: "{% for host in groups['masters'] %}{{ hostvars[host]['join_command'] }}{% endfor %}"
#  become: yes

- name: Join kubeadm step
  shell: "{{ kubetoken }}"
  become: yes
